from pathlib import Path
p=Path('preview-v05/index.html')
s=p.read_text()
s=s.replace("const APP_VERSION='0.5.0-alpha1';","const APP_VERSION='0.5.0-alpha2';")
s=s.replace(".trash{opacity:.75}.swipeHint", ".weatherDetail{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.weatherDetail div{background:#fff;border:1px solid #d9e9dd;border-radius:12px;padding:8px 4px;text-align:center}.weatherDetail small{display:block;color:var(--muted);font-size:9px}.weatherDetail b{font-size:12px}.timeline{border-left:2px solid #dbe6df;margin:12px 0 4px 8px;padding-left:14px}.timelineItem{position:relative;padding:4px 0 14px}.timelineItem:before{content:'';position:absolute;left:-20px;top:9px;width:9px;height:9px;border-radius:50%;background:var(--green);border:2px solid var(--bg)}.timelineItem.travel:before{background:#9aa5a0}.timelineItem b{display:block}.timelineItem small{color:var(--muted)}.trash{opacity:.75}.swipeHint")
old="async function endVisit(){const v=await activeVisit();if(v){v.endedAt=iso();await put('spotVisits',v)}return v}"
new="async function endVisit(){const s=await activeSession();if(!s)return null;const open=(await all('spotVisits')).filter(v=>active(v)&&v.sessionId===s.id&&!v.endedAt);if(!open.length)return null;const ended=iso();for(const v of open){v.endedAt=ended;await put('spotVisits',v)}return open[0]}"
s=s.replace(old,new)
old_start="async function renderDashboard(){"
old_end="function chooseHero(){"
a=s.index(old_start); b=s.index(old_end,a)
new_dash=r'''async function renderDashboard(){const [waters,spots,events,days]=await Promise.all(['waters','spots','events','days'].map(all));const wa=waters.filter(active),sp=spots.filter(active),ev=events.filter(active),da=days.filter(active);const catches=ev.filter(e=>e.type==='catch');const ctx=await currentContext();let hero=await setting('dashboardHero','');let html=`${hero?`<div class="hero"><img src="${hero}"><button class="heroAction" id="heroEdit">Foto ändern</button><div class="heroText"><div class="eyebrow" style="color:#dbece2">DEINE ANGEL-DATENBANK</div><h2>Fishing OS</h2><p>${catches.length} Fänge · ${wa.length} Gewässer · ${sp.length} Spots</p></div></div>`:`<div class="card"><div class="section" style="margin:0"><h2>Deine Angel-Datenbank</h2><button class="btn secondary" id="heroEdit">Titelbild</button></div><p class="muted">Privat, offline-first und vollständig nachbearbeitbar.</p></div>`}<div class="metrics"><div class="metric"><b>${catches.length}</b><small>Fänge</small></div><div class="metric"><b>${wa.length}</b><small>Gewässer</small></div><div class="metric"><b>${sp.length}</b><small>Spots</small></div><div class="metric"><b>${da.length}</b><small>Angeltage</small></div></div>`;
if(ctx.day){const w=await latestWeather(ctx.session?.id);const wd=w?.windDirection!=null?`${Math.round(w.windDirection)}°`: '–';html+=`<div class="section"><h2>Aktiver Angeltag</h2><span class="badge">läuft</span></div><div class="card session"><div class="sessionHead"><div><div class="sessionStatus"><span class="dot"></span>Angeltag aktiv</div><h2>${esc(ctx.water?.name||'Gewässer wählen')}</h2><div class="muted">${ctx.spot?esc(ctx.spot.name):'Unterwegs · kein Spot aktiv'}</div></div><b>${fmtDuration(ctx.day.startedAt)}</b></div><div class="sessionGrid"><div class="sessionCell"><small>Start</small><b>${fmtTime(ctx.day.startedAt)}</b></div><div class="sessionCell"><small>Spot</small><b>${ctx.visit?fmtDuration(ctx.visit.startedAt):'–'}</b></div><div class="sessionCell"><small>Wetter</small><b>${w?.temperature!=null?Math.round(w.temperature)+'°':'–'}</b></div></div>${w?`<div class="weatherDetail"><div><small>Luftdruck</small><b>${w.pressure!=null?Math.round(w.pressure)+' hPa':'–'}</b></div><div><small>Wind</small><b>${w.windSpeed!=null?Math.round(w.windSpeed)+' km/h':'–'}</b></div><div><small>Richtung</small><b>${wd}</b></div><div><small>Wolken</small><b>${w.cloudCover!=null?Math.round(w.cloudCover)+' %':'–'}</b></div></div><div class="small muted" style="margin-top:7px">Wetter ${w.status==='live'?'erfasst':'offline gespeichert'} · ${fmtTime(w.capturedAt)}</div>`:''}<div class="sessionActions"><button class="btn secondary" id="spotAction">${ctx.spot?'Spot beenden':'Spot starten'}</button><button class="btn secondary" id="waterChange">Gewässer wechseln</button></div><button class="btn danger full" id="dayFinish" style="margin-top:8px">Angeltag beenden</button></div><div class="section"><h2>Schnelleinträge</h2><button class="textbtn" id="manualWeather">Wetter ↻</button></div><div class="quick">${['catch','bite','lostInFight','follower','observation','lureLoss'].map((t,i)=>`<button data-event="${t}"><div class="bubble" style="background:${['#3f8f52','#e99522','#d95d4d','#3288d6','#7558d7','#68736e'][i]}">${EVENT_ICON[t]}</div><small>${EVENT_LABEL[t]}</small></button>`).join('')}</div>`}else html+=`<div class="section"><h2>Angeltag</h2></div><div class="card"><h2 style="margin-top:0">Bereit fürs Wasser?</h2><p class="muted">Starten → Gewässer wählen → Spot starten → angeln.</p><button class="btn full" id="dayStart">Angeltag starten</button></div>`;
html+=`<div class="section"><h2>Letzte Ereignisse</h2></div>${ev.sort((a,b)=>new Date(b.occurredAt||b.at||0)-new Date(a.occurredAt||a.at||0)).slice(0,5).map(e=>eventRow(e,waters,spots)).join('')||'<div class="empty">Noch keine Ereignisse.</div>'}`;$('#view').innerHTML=html;$('#heroEdit')?.addEventListener('click',chooseHero);$('#dayStart')?.addEventListener('click',startDay);$('#dayFinish')?.addEventListener('click',()=>confirm('Angeltag wirklich beenden?')&&finishDay());$('#waterChange')?.addEventListener('click',changeWater);$('#manualWeather')?.addEventListener('click',manualWeatherRefresh);$('#spotAction')?.addEventListener('click',async()=>{const c=await currentContext();if(c.spot)return stopSpot();showSpotPicker(c.session.waterId)});$$('[data-event]').forEach(b=>b.onclick=()=>quickEvent(b.dataset.event))}
'''
s=s[:a]+new_dash+s[b:]
old_start="async function renderJournal(){"
old_end="async function renderStats(){"
a=s.index(old_start); b=s.index(old_end,a)
new_journal=r'''async function renderJournal(){const [days,sessions,waters,events,visits,spots]=await Promise.all(['days','sessions','waters','events','spotVisits','spots'].map(all));$('#pageTitle').textContent='Tagebuch';const ds=days.filter(active).sort((a,b)=>new Date(b.startedAt||b.start||0)-new Date(a.startedAt||a.start||0));$('#view').innerHTML=`${ds.map(d=>{const ss=sessions.filter(s=>active(s)&&s.dayId===d.id).sort((a,b)=>new Date(a.startedAt)-new Date(b.startedAt)),names=ss.map(s=>waters.find(w=>w.id===s.waterId)?.name).filter(Boolean),ev=events.filter(e=>active(e)&&e.dayId===d.id);let timeline='';for(const sess of ss){const water=waters.find(w=>w.id===sess.waterId),vv=visits.filter(v=>active(v)&&v.sessionId===sess.id).sort((a,b)=>new Date(a.startedAt)-new Date(b.startedAt));timeline+=`<div class="timelineItem"><b>${esc(water?.name||'Gewässer')}</b><small>${fmtTime(sess.startedAt)}${sess.endedAt?' – '+fmtTime(sess.endedAt):' – läuft'}</small></div>`;let cursor=sess.startedAt;for(const v of vv){if(cursor&&new Date(v.startedAt)>new Date(cursor)+1000)timeline+=`<div class="timelineItem travel"><b>Unterwegs · kein Spot aktiv</b><small>${fmtTime(cursor)} – ${fmtTime(v.startedAt)} · ${fmtDuration(cursor,v.startedAt)}</small></div>`;const spot=spots.find(x=>x.id===v.spotId);timeline+=`<div class="timelineItem"><b>${esc(spot?.name||'Spot')}</b><small>${fmtTime(v.startedAt)} – ${v.endedAt?fmtTime(v.endedAt):'läuft'} · ${fmtDuration(v.startedAt,v.endedAt||iso())}</small></div>`;cursor=v.endedAt||iso()}const end=sess.endedAt||(d.endedAt?d.endedAt:iso());if(cursor&&new Date(end)>new Date(cursor)+1000)timeline+=`<div class="timelineItem travel"><b>Unterwegs · kein Spot aktiv</b><small>${fmtTime(cursor)} – ${sess.endedAt||d.endedAt?fmtTime(end):'jetzt'} · ${fmtDuration(cursor,end)}</small></div>`}return `<div class="card"><div class="section" style="margin:0"><div><h2 style="margin:0">${fmtDate(d.startedAt||d.start)}</h2><div class="muted">${names.join(' → ')||'Historischer Angeltag'}</div></div><span class="badge">${ev.filter(e=>e.type==='catch').length} Fänge</span></div><p>${fmtTime(d.startedAt||d.start)} – ${d.endedAt?fmtTime(d.endedAt):'läuft'} · ${fmtDuration(d.startedAt||d.start,d.endedAt||iso())}</p>${timeline?`<div class="timeline">${timeline}</div>`:''}</div>`}).join('')||'<div class="empty">Noch keine Angeltage.</div>'}`}
'''
s=s[:a]+new_journal+s[b:]
p.write_text(s)
